### ISSUE TITLE
Receiving data sent to the tunnel

### ISSUE THREAD

**Issue by Mamenekr** [iamlinhui/rpt#12]
Hello, I would like to ask what classes receive the data that is sent to the tunnel?

**Comment by iamlinhui** [comment]
https://github.com/iamlinhui/rpt/blob/e805e37674e675c6e47188d17bbc1f0c493648a9/rpt-server/src/main/java/cn/promptness/rpt/server/handler/RemoteHandler.java#L66
https://github.com/iamlinhui/rpt/blob/e805e37674e675c6e47188d17bbc1f0c493648a9/rpt-server/src/main/java/cn/promptness/rpt/server/executor/DataExecutor.java#L24
